<FONT size="10pt" color='Blue'> <center>Estimation des offres financières pour les appels d’offres basé sur les résultats historiques</center></FONT>

- **Dans ce notebook, vous trouverez la présentation des données que je souhaite utiliser pendant le projet**

#### importation des bibliotheques

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from IPython.display import display, Markdown
import missingno as msno

ModuleNotFoundError: No module named 'missingno'

In [2]:
df = pd.read_csv('Data_P1.csv')
df.head(5)

,Date et heure limite de remise des plis,Référence,Objet,Acheteur public,Type d'annonce,Procédure,Catégorie principale,Allotissement,Lieu d'exécution,Domaines d'activité,...,Agréments,"Prospectus, notices ou autres documents",Réunion,Visites des lieux,Variante,Contact Administratif,refConsultation,orgAcronyme,financial_data_json,error
0,31/12/2024 16:00,TAC_AO_26_24,TAC_AO_26_24 RELATIF AUX TRAVAUX DE REALISATIO...,M3 / ASTM/TMPA - AGENCE SPECIALE TANGER MEDITE...,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Travaux,NaN,FAHS-ANJRA,"Travaux / Travaux d’assainissement, d’eau pota...",...,-,-,-,NaN,Non,Nabil MEKSOUB | Email: n.meksoub@tangermed.ma ...,858102,o8p,NaN,NaN
1,31/12/2024 16:00,TMPA_AO_126_24,ETUDES D’EXECUTION ET TRAVAUX DE STABILISATION...,M3 / ASTM/TMPA - AGENCE SPECIALE TANGER MEDITE...,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Travaux,NaN,FAHS-ANJRA,Travaux / Terrassements / Travaux d'enrochemen...,...,-,-,-,NaN,Non,HICHAM BENTOUHAMI | Email: h.bentouhami@tanger...,858219,o8p,NaN,NaN
2,31/12/2024 16:00,TMSA_AOO_17_24,TMSA_AOO_17_24 - REALISATION DES PRESTATIONS M...,M3 / ASTM/TMPA - AGENCE SPECIALE TANGER MEDITE...,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Services,NaN,TANGER-ASSILAH,Services / Services courants / Recrutement,...,-,-,-,NaN,Non,ZINEB TIJANI | Email: achats.tmsa@tmsa.ma | Te...,858540,o8p,NaN,NaN
3,31/12/2024 14:30,12/SMTF/DM/FSH/2024,"LES TRAVAUX D’ETAIEMENT, DE RESTAURATION ET DE...",MHAI / MHAI - MINISTERE DES HABOUS ET DES AFFA...,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Travaux,NaN,AL HAOUZ,Travaux / Travaux de construction et d’aménage...,...,-,-,-,"19/12/2024 12:00, LA MOSQUEE « TINMEL » A TLAA...",Non,Jawahir Abourachid | Email: jawahir.mhai@gmail...,855218,f4g,NaN,NaN
4,31/12/2024 14:00,316/2024/APDN,TRAVAUX DE REMPLACEMENT DE 14 CLASSES SCOLAIRE...,CG / APPDESPPNR - AGENCE POUR LA PROMOTION ET ...,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Travaux,2 Lots,"Province d'Al Hoceima, Province de Tanounate, ...",Travaux / Travaux de construction et d’aménage...,...,NaN,NaN,NaN,NaN,NaN,Fatima Zahra HASSANI | Email: f.hassani@apdn.m...,856210,a1t,"[{""lot"": ""Lot 6 : TRAVAUX DE REMPLACEMENT DE 0...",NaN

- **La description des colonnes de la table de données**

- **date_heure_limite_remise_plis**  
  🔹 Date et heure exactes où les soumissions doivent être déposées.  
  🔹 Sert à analyser les délais de réponse et la réactivité des entreprises.  

- **reference**  
  🔹 Code ou identifiant unique attribué à l’appel d’offre par l’organisme émetteur.  
  🔹 Permet un suivi administratif et facilite les recherches.  

- **objet**  
  🔹 Description courte du but ou de la nature de l’appel d’offre.  
  🔹 Sert à comprendre rapidement la finalité du projet.  

- **acheteur_public**  
  🔹 Administration ou entité publique responsable de l’appel d’offre.  
  🔹 Utile pour identifier l’émetteur et établir un historique.  

- **type_annonce**  
  🔹 Nature de la publication (appel d’offre, attribution, annulation…).  
  🔹 Permet de filtrer selon l’état du processus.  

- **procedure**  
  🔹 Méthode de passation (ouverte, restreinte, négociée…).  
  🔹 Indique le cadre juridique et administratif de la consultation.  

- **categorie_principale**  
  🔹 Domaine principal : Travaux, Fournitures, Services, etc.  
  🔹 Sert à segmenter les projets par nature.  

- **allotissement**  
  🔹 Indique si le marché est divisé en lots.  
  🔹 Permet de savoir si des entreprises peuvent soumissionner sur une partie du projet.  

- **lieu_execution**  
  🔹 Localisation géographique prévue pour la réalisation du projet.  
  🔹 Utile pour les analyses spatiales.  

- **domaines_activite**  
  🔹 Secteurs économiques ou techniques concernés.  
  🔹 Permet de regrouper les appels d’offres par filière.  

- **agrements**  
  🔹 Certificats ou qualifications obligatoires pour participer.  
  🔹 Sert à analyser les barrières à l’entrée.  

- **documents_annexes**  
  🔹 Documents annexes fournis par l’acheteur (prospectus, notices…).  
  🔹 Contiennent souvent des informations techniques détaillées.  

- **reunion**  
  🔹 Informations sur une éventuelle réunion d’information ou de clarification.  
  🔹 Utile pour comprendre le niveau d’accompagnement fourni.  

- **visites_lieux**  
  🔹 Informations sur les visites préalables des sites concernés.  
  🔹 Sert à identifier les contraintes logistiques.  

- **variante**  
  🔹 Indique si des propositions alternatives aux spécifications sont autorisées.  
  🔹 Permet de voir la flexibilité de l’acheteur.  

- **contact_administratif**  
  🔹 Coordonnées de la personne ou du service chargé du suivi administratif.  
  🔹 Utile pour établir un réseau ou poser des questions.  

- **ref_consultation**  
  🔹 Identifiant interne du dossier de consultation.  
  🔹 Sert pour la traçabilité dans les systèmes internes.  

- **org_acronyme**  
  🔹 Acronyme officiel de l’organisation émettrice.  
  🔹 Permet un traitement plus rapide dans les analyses.  

- **financial_data_json**  
  🔹 Données financières structurées au format JSON (budget, montant estimatif, etc.).  
  🔹 Crucial pour les analyses budgétaires.  

- **error**  
  🔹 Champ contenant les éventuelles erreurs ou anomalies détectées lors de la collecte.  
  🔹 Permet de filtrer et nettoyer les données.

In [3]:
display(Markdown(f'- la dimension de la Table est : **{df.shape}**'))

- la dimension de la Table est : **(2133, 28)**

In [4]:
display(Markdown(f'- le nombres des Apples offres repeter est  : **{df.duplicated().sum()}**'))

- le nombres des Apples offres repeter est  : **6**

In [5]:
display(Markdown('**- Le nombre des valeurs nulles dans chaque colonne est :**'))
df= df.replace('-', pd.NA)
df.isna().sum()

**- Le nombre des valeurs nulles dans chaque colonne est :**

Date et heure limite de remise des plis                                                                              0
Référence                                                                                                            0
Objet                                                                                                                0
Acheteur public                                                                                                      0
Type d'annonce                                                                                                       0
Procédure                                                                                                            0
Catégorie principale                                                                                                 0
Allotissement                                                                                                     1978
Lieu d'exécution                                                                                                     3
Domaines d'activité                                                                                                  0
Adresse de retrait des dossiers                                                                                      0
Adresse de dépôt des offres                                                                                          0
Lieu d'ouverture des plis                                                                                            0
Prix d'acquisition des plans                                                                                         0
Estimation (en Dhs TTC)                                                                                            155
Réservé à la TPE et PME installées au Maroc, jeunes entreprises innovantes, Coopératives et auto-entrepreneurs     155
Caution provisoire                                                                                                 155
Qualifications                                                                                                    1793
Agréments                                                                                                         2050
Prospectus, notices ou autres documents                                                                           1874
Réunion                                                                                                           2126
Visites des lieux                                                                                                 1901
Variante                                                                                                           155
Contact Administratif                                                                                               94
refConsultation                                                                                                      0
orgAcronyme                                                                                                          0
financial_data_json                                                                                                524
error                                                                                                             2133
dtype: int64

- **meme si le des colonnes ne contient pas aucune des valeur manquant mais il contient des (-) et considerer comme valeur null puisque il a pas de signification**

In [6]:
display(Markdown(f'- Nombre de Marche distinctes dans la colonne  **Catégorie principale est : {df["Catégorie principale"].nunique()}**'))

- Nombre de Marche distinctes dans la colonne  **Catégorie principale est : 3**

In [7]:
df['Catégorie principale'].value_counts()

Catégorie principale
Services       911
Travaux        731
Fournitures    491
Name: count, dtype: int64

In [8]:
display(Markdown(f"""- Nombre de secteur distinctes dans la colonne **type_annonce est : {df["Type d'annonce"].nunique()}**"""))

- Nombre de secteur distinctes dans la colonne **type_annonce est : 1**

In [9]:
df["Type d'annonce"].value_counts()

Type d'annonce
Annonce de consultation    2133
Name: count, dtype: int64

In [10]:
display(Markdown(f'- Nombre de organisme_emetteur distinctes dans la colonne  **Procédure est : {df["Procédure"].nunique()}**'))

- Nombre de organisme_emetteur distinctes dans la colonne  **Procédure est : 11**

In [11]:
df['Procédure'].value_counts()

Procédure
Appel d'offres ouvert | Sur offre de prix                                1423
Appel d'offres ouvert simplifié | Sur offre de prix                       533
Appel d'offres ouvert | Au rabais / majoration                             62
Appel d'offres ouvert simplifié | Au rabais / majoration                   33
Consultation architecturale ouverte | Sur offre de prix                    32
Appel à manifestation d'intérêt | Sur offre de prix                        17
Marché négocié avec publicité préalable - Phase 1 | Sur offre de prix      13
Consultation architecturale ouverte simplifiée | Sur offre de prix         11
Enchère électronique inversée | Sur offre de prix                           5
Concours Architectural | Sur offre de prix                                  3
Appel d'offres avec préselection - Phase 1 | Sur offre de prix              1
Name: count, dtype: int64

In [12]:
display(Markdown(f"""- Nombre de region distinctes dans la colonne  **Prix d'acquisition des plans est : {df["Prix d'acquisition des plans"].nunique()}**"""))

- Nombre de region distinctes dans la colonne  **Prix d'acquisition des plans est : 5**

In [13]:
df["Prix d'acquisition des plans"].value_counts()

Prix d'acquisition des plans
0,00 MAD         2129
200,00 MAD          1
23 600,00 MAD       1
7 500,00 MAD        1
15,00 MAD           1
Name: count, dtype: int64

In [14]:
display(Markdown(f'- Nombre des ville distinctes dans la colonne  **Variante est : {df["Variante"].nunique()}**'))

- Nombre des ville distinctes dans la colonne  **Variante est : 2**

In [15]:
df['Variante'].value_counts()

Variante
Non    1964
Oui      14
Name: count, dtype: int64

In [16]:
display(Markdown(f'- Nombre des categorie de  complexite_projet distinctes dans la colonne  **financial_data_json est : {df["financial_data_json"].nunique()}**'))

- Nombre des categorie de  complexite_projet distinctes dans la colonne  **financial_data_json est : 1588**

#### apres le passage au traitement de donnes des valeurs null on a des features influencent pas sur la dicision de notre model et aussi les features qui ne varient pas.

In [23]:
df_utile=df.drop(['Allotissement','Qualifications','Agréments','Prospectus, notices ou autres documents','Réunion','Visites des lieux','error'],axis=1)

In [24]:
df_utile.shape

(2133, 21)

- **cette suppression est pour les colonnes qu'on plus de 50% des valeur Manquant**

- **maintent je pass a analyser les features unitile existe dans la base donnes**

In [25]:
df_utile = df_utile.drop([
    "Date et heure limite de remise des plis",
    "Objet",
    "Acheteur public",
    "Lieu d'exécution",
    "Adresse de retrait des dossiers",
    "Adresse de dépôt des offres",
    "Lieu d'ouverture des plis",
    "Agréments",
    "Prospectus, notices ou autres documents",
    "Réunion",
    "Visites des lieux",
    "refConsultation"
], axis=1, errors='ignore')

In [26]:
df_utile.shape

(2133, 13)

In [27]:
df_utile.head(10)

,Référence,Type d'annonce,Procédure,Catégorie principale,Domaines d'activité,Prix d'acquisition des plans,Estimation (en Dhs TTC),"Réservé à la TPE et PME installées au Maroc, jeunes entreprises innovantes, Coopératives et auto-entrepreneurs",Caution provisoire,Variante,Contact Administratif,orgAcronyme,financial_data_json
0,TAC_AO_26_24,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Travaux,"Travaux / Travaux d’assainissement, d’eau pota...","0,00 MAD","0,00",Non,"250 000,00 MAD",Non,Nabil MEKSOUB | Email: n.meksoub@tangermed.ma ...,o8p,NaN
1,TMPA_AO_126_24,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Travaux,Travaux / Terrassements / Travaux d'enrochemen...,"0,00 MAD","0,00",Non,"50 000,00 MAD",Non,HICHAM BENTOUHAMI | Email: h.bentouhami@tanger...,o8p,NaN
2,TMSA_AOO_17_24,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Services,Services / Services courants / Recrutement,"0,00 MAD","0,00",Non,"250 000,00 MAD",Non,ZINEB TIJANI | Email: achats.tmsa@tmsa.ma | Te...,o8p,NaN
3,12/SMTF/DM/FSH/2024,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Travaux,Travaux / Travaux de construction et d’aménage...,"0,00 MAD","0,00",Non,"550 000,00 MAD",Non,Jawahir Abourachid | Email: jawahir.mhai@gmail...,f4g,NaN
4,316/2024/APDN,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Travaux,Travaux / Travaux de construction et d’aménage...,"0,00 MAD",NaN,NaN,NaN,NaN,Fatima Zahra HASSANI | Email: f.hassani@apdn.m...,a1t,"[{""lot"": ""Lot 6 : TRAVAUX DE REMPLACEMENT DE 0..."
5,39/CPT/2024,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Travaux,"Travaux / Travaux d’assainissement, d’eau pota...","0,00 MAD","2 526 720,00",Oui,"48 000,00 MAD",Non,ABDELAAZIZ ABOULHOUCINE | Email: abdelazizaboo...,f9f,"[{""Entreprise"": ""GHADIL"", ""Enveloppes administ..."
6,11/2024,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Services,"Services / Nettoyage, gardiennage, entretien e...","0,00 MAD","244 800,00",Non,"30 000,00 MAD",Non,BOUAZZA LAMETI | Email: lametib@gmail.com | Te...,h5r,NaN
7,08/2024/SB,Annonce de consultation,Appel d'offres ouvert simplifié | Sur offre de...,Travaux,"Travaux / Travaux d’assainissement, d’eau pota...","0,00 MAD","180 720,00",Non,"3 500,00 MAD",Non,Radouane Bousfiha | Email: cusidibennour@gmail...,p1v,"[{""Entreprise"": ""INTELMED"", ""Enveloppes admini..."
8,13/2024,Annonce de consultation,Appel d'offres ouvert simplifié | Sur offre de...,Travaux,Travaux / Travaux d’électricité / Travaux d'en...,"0,00 MAD","44 756,55",Non,"890,00 MAD",Non,MOHAMMED AQBADOU | Email: communefraita@gmail....,j0w,NaN
9,02/2024/GAMDU,Annonce de consultation,Appel d'offres ouvert | Sur offre de prix,Services,"Services / Conseil, audit et assistance à mait...","200,00 MAD","1 044 000,00",Non,"0,00 MAD",Non,AMINA BOUTAKBOUT | Email: agadirmobilite@gmail...,g3h,NaN